INSERT INTO EMPLOYEES (FIRST_NAME, MIDDLE_NAME, LAST_NAME, SECOND_LAST_NAME, EMAIL, GENDER, IDENTIFICATION_NUMBER, PHONE, DATE_OF_BIRTH, SALARY, POSITION, EMPLOYEE_STATUS, HIRE_DATE, AVAILABLE_VACATION_DAYS, TAKEN_VACATION_DAYS, LAST_VACATION_DATE, IS_DELETED)
VALUES ('John', 'Doe', 'Smith', 'Johnson', 'john.doe@example.com', 'M', 123456789, '1234567890', '1980-05-10', 5000.00, 'Doctor', 'Active', '2020-01-01', 20, 5, '2023-01-15', 0);

INSERT INTO DOCTORS (ID, SPECIALTY, LICENSE_NUMBER, MEDICAL_CODE)
VALUES (1, 'Administración de la Salud', '12345', 'ABC6789');

INSERT INTO USERS (_NAME, _PASSWORD, _ROLE, CREATION_DATE, _STATUS, DOCTOR_ID, SECRETARY_ID, PATIENT_ID, IS_ADMIN)
VALUES ('jsmith', '123', 'Admin', GETDATE(), 'Active', 1, NULL, NULL, 1);




select * from EMPLOYEES
select * from DOCTORS
select * from USERS
select * from LOG_USERS


delete from EMPLOYEES
delete from DOCTORS
delete from USERS
delete from LOG_USERS